# Generated by Django 5.2.3 on 2025-07-12 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='نام رسته')),
                ('category_type', models.CharField(choices=[('SERVICE', 'خدمت'), ('PRODUCT', 'کالا'), ('BOTH', 'هر دو')], default='SERVICE', max_length=10, verbose_name='نوع رسته')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
            ],
            options={
                'verbose_name': 'رسته فعالیت',
                'verbose_name_plural': 'رسته\u200cهای فعالیت',
                'ordering': ['name'],
            },
        ),
    ]
