# Generated by Django 5.2.3 on 2025-07-12 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sectors', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activitycategory',
            name='category_type',
            field=models.CharField(choices=[('SERVICE', 'خدمت'), ('PRODUCT', 'کالا'), ('BOTH', 'کالا و خدمت')], default='SERVICE', max_length=10, verbose_name='نوع رسته'),
        ),
    ]
