# Generated by Django 5.2.3 on 2025-07-07 13:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_rename_full_name_user_first_name_user_last_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'default_permissions': ('add', 'change', 'delete', 'view'), 'permissions': []},
        ),
    ]
