# Generated by Django 5.2.3 on 2025-07-10 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('regions', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='activityarea',
            name='unique_activity_area',
        ),
        migrations.RemoveField(
            model_name='activityarea',
            name='province',
        ),
        migrations.AddConstraint(
            model_name='activityarea',
            constraint=models.UniqueConstraint(fields=('city', 'area'), name='unique_activity_area'),
        ),
    ]
