# Generated by Django 5.2.3 on 2025-07-12 20:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NavyBrand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='برند ناوگان')),
                ('logo', models.ImageField(upload_to='navy-brands', verbose_name='لوگو برند ناوگان')),
            ],
        ),
        migrations.CreateModel(
            name='NavySize',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='سایز ناوگان')),
                ('logo', models.ImageField(upload_to='navy-size', verbose_name='لوگو سایز ناوگان')),
            ],
        ),
        migrations.CreateModel(
            name='NavyType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='نوع ناوگان')),
                ('logo', models.ImageField(upload_to='navy-type', verbose_name='لوگو تایپ ناوگان')),
            ],
        ),
        migrations.CreateModel(
            name='NavyMain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='نام اصلی ناوگان')),
                ('brand', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='navies_by_brand', to='fleets.navybrand', verbose_name='برند')),
                ('size', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='navies_by_size', to='fleets.navysize', verbose_name='سایز')),
                ('type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='navies_by_type', to='fleets.navytype', verbose_name='نوع')),
            ],
        ),
    ]
