# Generated by Django 5.2.3 on 2025-07-12 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleets', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='navybrand',
            name='logo',
            field=models.ImageField(upload_to='files/navy-brands', verbose_name='لوگو برند ناوگان'),
        ),
        migrations.AlterField(
            model_name='navysize',
            name='logo',
            field=models.ImageField(upload_to='files/navy-size', verbose_name='لوگو سایز ناوگان'),
        ),
        migrations.AlterField(
            model_name='navytype',
            name='logo',
            field=models.ImageField(upload_to='files/navy-type', verbose_name='لوگو تایپ ناوگان'),
        ),
    ]
