# Generated by Django 5.2.3 on 2025-07-13 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleets', '0002_alter_navybrand_logo_alter_navysize_logo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='navymain',
            name='tip',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='تیپ ناوگان'),
        ),
        migrations.AddConstraint(
            model_name='navymain',
            constraint=models.UniqueConstraint(fields=('name', 'type', 'size', 'brand', 'tip'), name='unique_navy_combination'),
        ),
    ]
