# Generated by Django 5.2.3 on 2025-07-13 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleets', '0003_navymain_tip_navymain_unique_navy_combination'),
    ]

    operations = [
        migrations.AlterField(
            model_name='navymain',
            name='tip',
            field=models.CharField(max_length=100, verbose_name='تیپ ناوگان'),
        ),
    ]
