# Generated by Django 5.2.3 on 2025-07-13 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleets', '0004_alter_navymain_tip'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='navymain',
            name='unique_navy_combination',
        ),
        migrations.AddConstraint(
            model_name='navymain',
            constraint=models.UniqueConstraint(fields=('type', 'size', 'brand', 'tip'), name='unique_navy_combination'),
        ),
    ]
