# Generated by Django 5.2.3 on 2025-07-13 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleets', '0005_remove_navymain_unique_navy_combination_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='navybrand',
            name='sizes',
            field=models.ManyToManyField(related_name='brands', to='fleets.navysize'),
        ),
        migrations.AddField(
            model_name='navysize',
            name='types',
            field=models.ManyToManyField(related_name='sizes', to='fleets.navytype'),
        ),
    ]
